export const ADD_TO_WEATHER_LIST = 'ADD_TO_WEATHER_LIST';
export const REMOVE_FROM_WEATHER_LIST = 'REMOVE_FROM_WEATHER_LIST';
export const GET_WEATHER = 'GET_WEATHER';
export const GET_WEATHER_BY_CITY = 'GET_WEATHER_BY_CITY';
export const ADD_TO_CITY_LIST = 'ADD_TO_CITY_LIST';
